[package]
name = "nod"
version = "0.1.2"
edition = "2018"
authors = ["Luke Street <luke@street.dev>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/encounter/nod-rs"
documentation = "https://docs.rs/nod"
readme = "README.md"
description = """
Rust library and CLI tool for reading GameCube and Wii disc images.
"""
keywords = ["gamecube", "wii", "iso", "nfs", "gcm"]
categories = ["command-line-utilities", "parser-implementations"]

[[bin]]
name = "nodtool"
path = "src/bin.rs"

[dependencies]
aes = "0.7.4"
anyhow = "1.0.53"
binread = "2.1.1"
block-modes = "0.8.1"
clap = "2.33.3"
encoding_rs = "0.8.28"
file-size = "1.0.3"
sha-1 = "0.9.7"
thiserror = "1.0.30"
