name: build

on: [ push, pull_request ]

jobs:
  default:
    name: Default
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, 1.35.0, nightly ]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.toolchain }}
          path: |
            target/release/nodtool
            target/release/nodtool.exe
